// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for Ghost Route.
/// Replace with a production Firebase project via: flutterfire configure
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS8DjtMjaDXSsuNqUqBH4Oz4rQr-qtNl0',
    appId: '1:977641016485:android:f3090ee215d70af436514c',
    messagingSenderId: '977641016485',
    projectId: 'ghostroute-7d157',
    storageBucket: 'ghostroute-7d157.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKI55KUfGB0pnt9InuoJ5lLFVPHJ2oKno',
    appId: '1:977641016485:web:d47806c3a6597f0c36514c',
    messagingSenderId: '977641016485',
    projectId: 'ghostroute-7d157',
    authDomain: 'ghostroute-7d157.firebaseapp.com',
    storageBucket: 'ghostroute-7d157.firebasestorage.app',
    measurementId: 'G-KLCKCM3N3D',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT1vcrKM50-iSOKBAUgXrCsEm2K09y3ic',
    appId: '1:977641016485:ios:36e83ffbf9d5c4a736514c',
    messagingSenderId: '977641016485',
    projectId: 'ghostroute-7d157',
    storageBucket: 'ghostroute-7d157.firebasestorage.app',
    iosBundleId: 'com.yencode.ghostroute',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT1vcrKM50-iSOKBAUgXrCsEm2K09y3ic',
    appId: '1:977641016485:ios:36e83ffbf9d5c4a736514c',
    messagingSenderId: '977641016485',
    projectId: 'ghostroute-7d157',
    storageBucket: 'ghostroute-7d157.firebasestorage.app',
    iosBundleId: 'com.yencode.ghostroute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKI55KUfGB0pnt9InuoJ5lLFVPHJ2oKno',
    appId: '1:977641016485:web:fc1534afa3e6ad6d36514c',
    messagingSenderId: '977641016485',
    projectId: 'ghostroute-7d157',
    authDomain: 'ghostroute-7d157.firebaseapp.com',
    storageBucket: 'ghostroute-7d157.firebasestorage.app',
    measurementId: 'G-C1WFY8Z14V',
  );

}