/** Default subscription plans (index 0–1). Amounts in USD cents. Used by seed script and startup bootstrap. */
export const defaultPlans = [
  {
    index: 0,
    name: 'platinumMonthly',
    tier: 'platinum',
    interval: 'monthly',
    durationDays: 30,
    amount: 500,
    currency: 'USD',
    devices: 5,
    displayName: 'Platinum Monthly (5 devices)',
    intervalLabel: 'Monthly',
    period: 'per month',
    price: '$5.00',
    description: 'Best for individuals & families',
    badge: null,
  },
  {
    index: 1,
    name: 'platinumYearly',
    tier: 'platinum',
    interval: 'yearly',
    durationDays: 365,
    amount: 3500,
    currency: 'USD',
    devices: 5,
    displayName: 'Platinum Yearly (5 devices)',
    intervalLabel: 'Yearly',
    period: 'per year',
    price: '$35.00',
    description: 'Save 42% · Full access',
    badge: 'Best value',
  },
];
