export const wireguardPremiumServers = [
  {
    id: 1,
    serverName: 'Vultr US New Jersey',
    country: 'United States',
    city: 'New Jersey',
    host: '45.77.155.240',
    port: 51820,
    publicKey: 'bV2EYFUTWwiEG9Fa8dnLk6xu4uLSqg4swUOHQMSNnTA=',
    clientPrivateKey: 'qANh09vi3cj7vvUyxSxBBpt8W21+0cCRGtAFUsqsxUo=',
    address: '10.8.0.2/24',
    dns: '1.1.1.1',
    allowedIPs: '0.0.0.0/0, ::/0',
    persistentKeepalive: 25,
  },
  {
    id: 2,
    serverName: 'Vultr Singapore',
    country: 'Singapore',
    city: 'Singapore',
    host: '45.76.144.194',
    port: 51820,
    publicKey: 'a3ntai53sHRqnFdzH74h6JI8fLt6pbyHlRcO6QqUzl8=',
    clientPrivateKey: '0EF9tP1AqTT60uV/wkNuyuUCzaXGv0RbDPun29v2tEg=',
    address: '10.0.0.2/24',
    dns: '1.1.1.1',
    allowedIPs: '0.0.0.0/0, ::/0',
    persistentKeepalive: 25,
  },
  {
    id: 3,
    serverName: 'Vultr India Mumbai',
    country: 'India',
    city: 'Mumbai',
    host: 'MUMBAI_SERVER_PUBLIC_IP',
    port: 51820,
    publicKey: 'MUMBAI_SERVER_PUBLIC_KEY',
    clientPrivateKey: 'MUMBAI_CLIENT_PRIVATE_KEY',
    address: '10.9.0.2/24',
    dns: '1.1.1.1',
    allowedIPs: '0.0.0.0/0, ::/0',
    persistentKeepalive: 25,
  },
  {
    id: 4,
    serverName: 'Vultr Japan Tokyo',
    country: 'Japan',
    city: 'Tokyo',
    host: 'JAPAN_SERVER_PUBLIC_IP',
    port: 51820,
    publicKey: 'JAPAN_SERVER_PUBLIC_KEY',
    clientPrivateKey: 'JAPAN_CLIENT_PRIVATE_KEY',
    address: '10.10.0.2/24',
    dns: '1.1.1.1',
    allowedIPs: '0.0.0.0/0, ::/0',
    persistentKeepalive: 25,
  },
];

